/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './seed.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from '@angular/core/src/i18n/tokens';
import * as import6 from './seed.service';
class SeedModuleInjector extends import0.NgModuleInjector<import1.SeedModule> {
  _CommonModule_0:import2.CommonModule;
  _SeedModule_1:import1.SeedModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  __SeedService_3:any;
  constructor(parent:import4.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import5.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _SeedService_3():any {
    if ((this.__SeedService_3 == null)) { (this.__SeedService_3 = import1.seedServiceFactory()); }
    return this.__SeedService_3;
  }
  createInternal():import1.SeedModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SeedModule_1 = new import1.SeedModule();
    return this._SeedModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.SeedModule)) { return this._SeedModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import6.SeedService)) { return this._SeedService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SeedModuleNgFactory:import0.NgModuleFactory<import1.SeedModule> = new import0.NgModuleFactory(SeedModuleInjector,import1.SeedModule);